services:

  mysql:
    image: mysql:8.0
    container_name: mysql-healthcare
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_HEALTHCARE}
      MYSQL_ROOT_PASSWORD: ${DB_HEALTHCARE_ROOT_PASSWORD}
      MYSQL_USER: ${DB_HEALTHCARE_USER}
      MYSQL_PASSWORD: ${DB_HEALTHCARE_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - "3309:3306"
    networks:
      - healthcare-network

networks:
  healthcare-network:
    driver: bridge

