services:

  mysql:
    image: mysql:8.0
    container_name: mysql-healthcare
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_HEALTHCARE}
      MYSQL_ROOT_PASSWORD: ${DB_HEALTHCARE_ROOT_PASSWORD}
      MYSQL_USER: ${DB_HEALTHCARE_USER}
      MYSQL_PASSWORD: ${DB_HEALTHCARE_PASSWORD}
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - healthcare-network

  consul:
    image: hashicorp/consul:1.21.3
    container_name: consul
    ports:
      - "8500:8500"
    command: consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -data-dir=/consul/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - healthcare-network

  ms-patient:
    image: enzogavini/patient:latest
    container_name: ms-patient
    ports:
      - "8085:8085"
    environment:
      SPRING_APPLICATION_NAME: patient
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_HEALTHCARE}?allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_HEALTHCARE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_HEALTHCARE_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - healthcare-network

  ms-ui-service:
    image: enzogavini/ui-service:latest
    container_name: ms-ui-service
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: ui-service
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    depends_on:
      consul:
        condition: service_healthy
      ms-patient:
        condition: service_started
    networks:
      - healthcare-network

networks:
  healthcare-network:
    driver: bridge