spring:
  application:
    name: patient
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/${DB_HEALTHCARE}
    username: ${DB_HEALTHCARE_USER}
    password: ${DB_HEALTHCARE_PASSWORD}

  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8085