spring:
  application:
    name: ui-service

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true

server:
  port: 8090
